repos:
  - repo: https://github.com/myint/autoflake.git
    rev: "v2.0.1"
    hooks:
      - id: autoflake
        args:
          - "--in-place"
          - "--remove-unused-variables"
          - "--remove-all-unused-imports"
          - "--ignore-init-module-imports"
  - repo: https://github.com/timothycrosley/isort
    rev: "5.12.0"
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: "23.1.0"
    hooks:
      - id: black
        additional_dependencies: ["click==8.0.4"]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.0.1"
    hooks:
      - id: mypy
        # args:
        #   - "--no-strict-optional"
        #   - "--ignore-missing-imports"
        additional_dependencies:
          - "pydantic"
          - "types-python-dateutil==2.8.3"
          - "types-pyYAML"
          - "types-requests"
  - repo: https://github.com/pycqa/flake8
    rev: "6.0.0"
    hooks:
      - id: flake8
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v2.7.1"
    hooks:
      - id: prettier
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: "v8.34.0"
    hooks:
      - id: eslint
        additional_dependencies:
          - eslint@8.21.0
        args:
          - "--fix"
        files: \.[jt]sx?$ # *.js, *.jsx, *.ts and *.tsx
        types: [file]
